module.exports = {
  type: 'mysql',
  // host: process.env.DB_HOST,
  // port: process.env.DB_PORT,
  // username: process.env.DB_USER_NAME,
  // password: process.env.DB_PASSWORD,
  // database: process.env.DB_NAME,
  host: "localhost",
  port: "3306",
  username: "tuanla",
  password: "Fart_20011998",
  database: "db_kumiai_test",
  entities: ['dist/app/database/entities/*.entity.{js,ts}'],
  migrations: ['dist/app/database/migrations/**/*.{js,ts}'],
  // seeds: ['dist/database/seeds/*.seed.{js,ts}'],
  // factories: ['dist/database/factories/*.factory.{js,ts}'],
  synchronize: false,
  logging: false,
  migrationsTableName: 'system_migrations',
  cli: {
    entitiesDir: 'src/app/database/entities',
    migrationsDir: 'src/app/database/migrations',
    subscribersDir: 'src/app/subscriber/develop',
    // seedersDir: 'src/database/seeds',
    // factoriesDir: 'src/database/factories',
  },
};
